import {
    ElAlert,
    ElAside,
    ElButton,
    ElSelect,
    ElRow,
    ElCol,
    ElForm,
    ElFormItem,
    ElInput,
    ElTabs,
    ElTabPane,
    ElCheckbox,
    ElIcon,
    ElDivider,
    ElBacktop,
    ElDropdown,
    ElDropdownMenu,
    ElDropdownItem,
    ElContainer,
    ElHeader,
    ElSlider,
    ElMain,
    ElFooter,
    ElMenu,
    ElMenuItem,
    ElSubMenu,
    ElMenuItemGroup,
    ElRadio,
    ElRadioButton,
    ElRadioGroup,
    ElTooltip,
    ElScrollbar,
    ElTableColumn,
    ElTag,
    ElTable,
} from 'element-plus';

// 所需的组件
export const components = [
    ElAlert,
    ElAside,
    ElButton,
    ElSelect,
    ElRow,
    ElCol,
    ElForm,
    ElFormItem,
    ElInput,
    ElTabs,
    ElTabPane,
    ElCheckbox,
    ElIcon,
    ElDivider,
    ElBacktop,
    ElDropdown,
    ElDropdownMenu,
    ElDropdownItem,
    ElContainer,
    ElHeader,
    ElSlider,
    ElMain,
    ElFooter,
    ElMenu,
    ElMenuItem,
    ElSubMenu,
    ElMenuItemGroup,
    ElRadio,
    ElRadioButton,
    ElRadioGroup,
    ElTooltip,
    ElScrollbar,
    ElTableColumn,
    ElTag,
    ElTable,
]

export default (app) => {
    components.forEach((component) => {
      app.component(component.name,component)
    })
}